export const AUTHENTICATION_LOGIN_ERRORED = 'AUTHENTICATION_LOGIN_ERRORED';
export const AUTHENTICATION_LOGIN_LOADING = 'AUTHENTICATION_LOGIN_LOADING';
export const AUTHENTICATION_LOGIN_SUCCESS = 'AUTHENTICATION_LOGIN_SUCCESS';
export const AUTHENTICATION_LOGOUT_SUCCESS = 'AUTHENTICATION_LOGOUT_SUCCESS';
