export const RESTAURANT_LOADING = 'RESTAURANT_LOADING';
export const RESTAURANT_ERRORED = 'RESTAURANT_ERRORED';
export const RESTAURANT_SUCCESS = 'RESTAURANT_SUCCESS';
export const RESTAURANT_OPEN = 'RESTAURANT_OPEN';
export const RESTAURANT_CLOSED = 'RESTAURANT_CLOSED';
