export const RESTAURANT_LOADING = 'RESTAURANT_LOADING';
export const RESTAURANT_ERRORED = 'RESTAURANT_ERRORED';
export const RESTAURANT_SUCCESS = 'RESTAURANT_SUCCESS';
export const RESTAURANT_OPEN = 'RESTAURANT_OPEN';
export const RESTAURANT_CLOSED = 'RESTAURANT_CLOSED';
export const RESTAURANT_RATING = 'RESTAURANT_RATING';
export const RESTAURANT_RATINGS = 'RESTAURANT_RATINGS';
export const RESTAURANT_ADD_RATINGS = 'RESTAURANT_ADD_RATINGS';
export const RESTAURANT_OPEN_RATINGFORM = 'RESTAURANT_OPEN_RATINGFORM';

